name: Scoop Bucket Updater

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour at minute 0
  workflow_dispatch: # Manual trigger

jobs:
  update-bucket:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install dependencies (requests, if necessary)
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
   
    # Step 5: Configure Git for GitHub
    - name: Configure Git for GitHub
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
 
    # Step 6: Run the Python script
    - name: Run Scoop Bucket Updater Script
      run: |
        python updatescript.py
    
    # Step 6: Check for changes
    # - name: Check for changes
      # run: |
        # git status
        # git diff
    
    # Step 7: pull push
    - name: Commit and push changes to GitHub
      run: |
        git push
        
    - name: Gitlab Sync
      uses: kujov/gitlab-sync@2.0.0
      with:
        # GitLab repo URL
        gitlab_url: https://gitlab.com/ingenarel/ingenarel-scoop-bucket
        # GitLab username
        username: ingenarel
        # GitLab token
        gitlab_pat: ${{ secrets.GITLAB_TOKEN }}
          
