name: Scoop Bucket Updater

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour at minute 0
  workflow_dispatch: # Manual trigger

jobs:
  update-bucket:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install dependencies (requests, if necessary)
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Step 4: Run the Python script
    - name: Run Scoop Bucket Updater Script
      run: |
        python updatescript.py
    
    
    # Step 5: Configure Git for GitHub
    - name: Configure Git for GitHub
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    # Step 6: Check for changes
    - name: Check for changes
      run: |
        git status
        git diff
    
    # Step 7: Commit and push changes to GitHub
    - name: Commit and push changes to GitHub
      run: |
        git add .
        git commit -m "Automated bucket update" || echo "No changes to commit"
        git push origin master
    
    # Step 8: Configure GitLab credentials
    - name: Configure GitLab remote
      run: |
        git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/ingenarel/ingenarel-scoop-bucket.git
        git fetch gitlab master
        git rebase gitlab/master || echo "No rebase needed"
    # Step 9: Push changes to GitLab
    - name: Push changes to GitLab
      run: |
        git push gitlab master
